### PR TITLE
info: show whether unimplemented exercises have canonical data

### LINKED ISSUE #481: info: indicate exercises that lack canonical data

### PR DESCRIPTION
**Pull request by ee7**
Closes: #481

To illustrate, let's consider the output of `configlet info` for the Elixir track.

Before this PR (and with #566):

```
[...]

There are 8 non-deprecated exercises in `exercism/problem-specifications` that
are both unimplemented and not in the track config `exercises.foregone` array:
error-handling
hangman
killer-sudoku-helper
ledger
lens-person
paasio
state-of-tic-tac-toe
tree-building

[...]
```

With this PR:

```
[...]

There are 8 non-deprecated exercises in `exercism/problem-specifications` that
are both unimplemented and not in the track config `exercises.foregone` array:
("NC" means the exercise lacks canonical data)
NC  error-handling
NC  hangman
    killer-sudoku-helper
NC  ledger
NC  lens-person
NC  paasio
    state-of-tic-tac-toe
NC  tree-building

[...]
```

Feel free to suggest improvements to the display format. Pinging @angelikatyborska as the feature requester - see https://github.com/exercism/configlet/issues/180#issuecomment-934344148.

I think I prefer:
- Indicating the status in the left column, because the indications will be further from the slug if we align on the right using the longest slug length.
- Indicating the lack of canonical data, rather than the presence of it. A track is more likely to implement every exercise with canonical data than every exercise without canonical data - so, this way round, that track doesn't get a confusing blank column.

But there are some other options in https://github.com/exercism/configlet/issues/481#issuecomment-997251455.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
The change looks good, I'm only unsure about the "NC" prefix. I know it is being explained above it, but I'm not sure it would be immediately obvious to maintainers. I'd be curious in hearing @angelikatyborska's opinion.

**Comment by kotp** [comment]
When doing `bin/configlet info` it would be something to put a heading in the top where a legend can show what is what.

We already have informational blurbs as headers for that information, placing a legend there makes sense to me.

**Comment by ee7** [comment]
> The change looks good, I'm only unsure about the "NC" prefix.

I don't love it either. It's not obvious what it stands for (even to me). Perhaps "no `canonical-data.json`"? Or "non-canonical"?

Maybe a table for now? Looking again, it feels more consistent to have the slug on the left, and to omit border `|` characters.

So I'm leaning towards one of the below. Any thoughts?
 
```
There are 8 non-deprecated exercises in `exercism/problem-specifications` that
are both unimplemented and not in the track config `exercises.foregone` array:

Exercise               Has canonical data?
--------------------   -------------------
error-handling         no
hangman                no
killer-sudoku-helper   yes
ledger                 no
lens-person            no
paasio                 no
state-of-tic-tac-toe   yes
tree-building          no
```

or sorting first by canonical data presence:

```
Exercise               Has canonical data?
--------------------   -------------------
killer-sudoku-helper   yes
state-of-tic-tac-toe   yes
error-handling         no
hangman                no
ledger                 no
lens-person            no
paasio                 no
tree-building          no
```

Here I'm avoiding using characters like ✔️, ❌, or `o` or `x` (see https://en.wikipedia.org/wiki/Check_mark#International_differences), or a blank space to indicate "no". The below situation would be especially unclear.

```
Exercise               Has canonical data?
--------------------   -------------------
error-handling         x
hangman                x
ledger                 x
lens-person            x
paasio                 x
tree-building          x
```

An example full output with this PR currently is:
```
Concepts that aren't a prerequisite for any Practice Exercise:
access-behaviour
alias
behaviours
docs
dynamic-dispatch
import
io
links
try-rescue
try-rescue-else-after
typespecs
use

Concepts that aren't practiced by any Practice Exercise:
access-behaviour
alias
ast
behaviours
docs
dynamic-dispatch
import
io
links
streams
try-rescue
try-rescue-else-after
typespecs
use
with

Concepts that are a prerequisite, but aren't practiced by any Practice Exercise:
ast
streams
with

There are 8 non-deprecated exercises in `exercism/problem-specifications` that
are both unimplemented and not in the track config `exercises.foregone` array:
("NC" means the exercise lacks canonical data)
NC  error-handling
NC  hangman
    killer-sudoku-helper
NC  ledger
NC  lens-person
NC  paasio
    state-of-tic-tac-toe
NC  tree-building

Track summary:
 39 Concept Exercises (plus 1 work-in-progress)
115 Practice Exercises (plus 0 work-in-progress)
154 Exercises in total (plus 1 work-in-progress)
 59 Concepts
```

**Comment by ee7** [comment]
Another option for your consideration:

```
There are 8 non-deprecated exercises in `exercism/problem-specifications` that
are both unimplemented and not in the track config `exercises.foregone` array:

With canonical data:
killer-sudoku-helper
state-of-tic-tac-toe

Without canonical data:
error-handling
hangman
ledger
lens-person
paasio
tree-building
```

**Comment by ErikSchierboom** [comment]
> Another option for your consideration:

I quite like this. It's plain and simple.

**Comment by ee7** [comment]
> I quite like this. It's plain and simple.

OK. I'll implement that.

To any others reading this: yell at me later if you hate it.

**Comment by ee7** [comment]
Please see commit message in https://github.com/exercism/configlet/pull/567/commits/4899199b2bee9695b36e64c2471de945af26a013

The code is a bit verbose (and naming variables is hard), but at least it produces the desired output.

Edit 1: refactored via the somewhat-obscure [`system.once`](https://github.com/nim-lang/Nim/blob/278ecad973c6581aeea0a6ff9372109b0dd6df5e/lib/system.nim#L3053-L3068).
Edit 2: ...and without it.

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
