### PR TITLE
🤖 Update labels

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This PR adds:

- A `.github/labels.yml` file containing this repository's labels
- An `.appends/.github/labels.yml` file, which contains all the repository-specific labels currently used in this repo.
- A `.github/workflows/sync-labels.yml` workflow to automatically synchronize this repository's labels

With this setup, the labels that can be used in this repo are all defined in a single file: the `.github/labels.yml` file. The `sync-labels.yml` workflow automatically runs whenever this file changes, and will update the repository's label to match the labels defined in the `.github/labels.yml` file. Note that is will remove any labels _not_ in the `.github/labels.yml` file, so be careful with removing labels from the `.github/labels.yml` file.

The `.github/labels.yml` file is auto-generated by concatenating these two files:

- The Exercism-wide labels defined in https://github.com/exercism/org-wide-files/blob/main/global-files/.github/labels.yml
- The repo-specific labels defined in `.appends/.github/labels.yml`

Whenever one of these two files change, a pull request is automatically submitted to update the `.github/labels.yml`  file. Merging that pull request will then trigger the sync-labels workflow, and the labels will be updated.

With this setup, we are able to guarantee that each repository can use both the Exercism-wide labels and any track-specific labels.

## Tracking

https://github.com/exercism/v3-launch/issues/41

### CODE REVIEW

**Comment by ee7** [comment]
Draft because I don't want this to be auto-merged - I'll nitpick the commit message.

**Comment by ErikSchierboom** [comment]
@ee7 Totally fine by me :) We do want these merged sometime soon-ish, as the tasks functionality on the website will depend on the labels being present.

**Comment by ee7** [comment]
Questions:
1. Do we want the configlet repo to have this? (I assume your answer is "yes, because then people can find issues to work on in configlet")
2. If yes, how should the `configlet` repo adapt its existing labels? Would you suggest that they're migrated to the `x:` format where appropriate? For example, should `kind:ci` become `x:type/ci`? 

I guess we'd end up with two "kind enums" - e.g. `kind: build` (perhaps changed to `type/build`), but the upstream `x:type/ci`. Is there anything better? I guess things like `x:type/build` and `x:type/tests` are too specific/confusing to add upstream.

**Comment by ErikSchierboom** [comment]
> Do we want the configlet repo to have this? (I assume your answer is "yes, because then people can find issues to work on in configlet")

That is correct :)

> If yes, how should the configlet repo adapt its existing labels? Would you suggest that they're migrated to the x: format where appropriate? For example, should kind:ci become x:type/ci?
> 
> I guess we'd end up with two "kind enums" - e.g. kind: build (perhaps changed to type/build), but the upstream x:type/ci. Is there anything better? 

Repos are allowed to decide for themselves.

> I guess things like x:type/build and x:type/tests are too specific/confusing to add upstream.

Yeah, I think they are a bit too specific/confusing.

What we _could_ do is to use the new Exercism-wide labels, but also add our own `x:type/build` and `x:type/tests` labels. There is nothing that prevents us from doing that and it shouldn't break anything. We'd also need to add one of the supported labels to have it show up properly, but this might be a good enough trade-off?

**Review by ee7 — COMMENTED** [review]
Edit: see also https://github.com/exercism/docs/issues/149

More questions:
3. Do we intend that every PR on Exercism is taggable with one of `x:module`?
4. Do we intend that every PR on Exercism is taggable with one of `x:type`?

I assume the answer is "no".

It seems like no `configlet` issue/PR can have an `x:module` label, and it's unclear to me if one can have a `x:type` label.

From [the docs]( https://github.com/exercism/docs/blob/eb4abf37c5a7a51f9865928d7719721016cbe293/product/tasks.md):

> ### Module tag
> 
> The `x:module/<value>` labels indicate what part of Exercism the contributor will be working on.
> 
> | Tag                          | Description                 |
> | ---------------------------- | --------------------------- |
> | `x:module/analyzer`          | Work on Analyzers           |
> | `x:module/concept`           | Work on Concepts            |
> | `x:module/concept-exercise`  | Work on Concept Exercises   |
> | `x:module/generator`         | Work on Exercise generators |
> | `x:module/practice-exercise` | Work on Practice Exercises  |
> | `x:module/representer`       | Work on Representers        |
> | `x:module/test-runner`       | Work on Test Runners        |



> ### Type tag
> 
> The `x:type/<value>` labels describe how much Exercism knowledge is required by the contributor.
> 
> | Tag              | Description                                                    |
> | ---------------- | -------------------------------------------------------------- |
> | `x:type/ci`      | Work on Continuous Integration (e.g. GitHub Actions workflows) |
> | `x:type/coding`  | Work on code that will run in production                       |
> | `x:type/content` | Work on content (e.g. exercises, concepts)                     |
> | `x:type/docker`  | Work on Dockerfiles                                            |
> | `x:type/docs`    | Work on Documentation                                          |

**Comment by ErikSchierboom** [comment]
> 3. Do we intend that every PR on Exercism is taggable with one of x:module?
> 4. Do we intend that every PR on Exercism is taggable with one of x:type?
>
> I assume the answer is "no".

You assumed correctly :) For an issue to be marked as a task, it just has to have _one_ of the `x:` labels we support. We might want add more options later on, but not currently.

**Review by ee7 — APPROVED** [review]
Merging.

**Comment by ee7** [comment]
Note to self: the `sync-labels` workflow had the below effect.

It seems like the workflow doesn't mention the diff when a label is updated. In this case, I want to know what was "updated" with the `kind: build` label. I don't think that I changed its description or color in the time since this PR was opened.

#### Updated labels
```
label {Name:kind: build Description:Non-.nim changes that affect the release binary Color:b15928} updated on: exercism/configlet
label {Name:v3-migration 🤖 Description:Preparing for Exercism v3 Color:e99695} updated on: exercism/configlet
```

#### Deleted labels
```
label: x:size/m deleted from: exercism/configlet
label: x:size/l deleted from: exercism/configlet
label: x:size/xl deleted from: exercism/configlet
label: x:size/xs deleted from: exercism/configlet
label: x:size/s deleted from: exercism/configlet
```

#### Created labels
```
label: {Name:x:size/tiny Description:Tiny amount of work Color:4836bf} created on: exercism/configlet
label: {Name:x:size/small Description:Small amount of work Color:4836bf} created on: exercism/configlet
label: {Name:x:size/medium Description:Medium amount of work Color:4836bf} created on: exercism/configlet
label: {Name:x:size/large Description:Large amount of work Color:4836bf} created on: exercism/configlet
label: {Name:x:size/massive Description:Massive amount of work Color:4836bf} created on: exercism/configlet
label: {Name:reputation/contributed_code/minor Description:Decreases the number of reputation points awarded by this PR Color:fcfa9f} created on: exercism/configlet
label: {Name:reputation/contributed_code/major Description:Increases the number of reputation points awarded by this PR Color:fcfa9f} created on: exercism/configlet
```

#### Unchanged labels
```
label: {Name:status: wont do/fix Description:This will not be worked on Color:EEEEEE} not changed on exercism/configlet
label: {Name:x:action/create Description:Work on something from scratch Color:6f60d2} not changed on exercism/configlet
label: {Name:x:action/fix Description:Fix an issue Color:6f60d2} not changed on exercism/configlet
label: {Name:x:action/improve Description:Improve existing functionality/content Color:6f60d2} not changed on exercism/configlet
label: {Name:x:action/proofread Description:Proofread text Color:6f60d2} not changed on exercism/configlet
label: {Name:x:action/sync Description:Sync content with its latest version Color:6f60d2} not changed on exercism/configlet
label: {Name:x:knowledge/none Description:No existing Exercism knowledge required Color:604fcd} not changed on exercism/configlet
label: {Name:x:knowledge/elementary Description:Little Exercism knowledge required Color:604fcd} not changed on exercism/configlet
label: {Name:x:knowledge/intermediate Description:Quite a bit of Exercism knowledge required Color:604fcd} not changed on exercism/configlet
label: {Name:x:knowledge/advanced Description:Comprehensive Exercism knowledge required Color:604fcd} not changed on exercism/configlet
label: {Name:x:module/analyzer Description:Work on Analyzers Color:5240c9} not changed on exercism/configlet
label: {Name:x:module/concept Description:Work on Concepts Color:5240c9} not changed on exercism/configlet
label: {Name:x:module/concept-exercise Description:Work on Concept Exercises Color:5240c9} not changed on exercism/configlet
label: {Name:x:module/generator Description:Work on Exercise generators Color:5240c9} not changed on exercism/configlet
label: {Name:x:module/practice-exercise Description:Work on Practice Exercises Color:5240c9} not changed on exercism/configlet
label: {Name:x:module/representer Description:Work on Representers Color:5240c9} not changed on exercism/configlet
label: {Name:x:module/test-runner Description:Work on Test Runners Color:5240c9} not changed on exercism/configlet
label: {Name:cmd: lint Description: Color:a6cee3} not changed on exercism/configlet
label: {Name:cmd: sync Description: Color:1f78b4} not changed on exercism/configlet
label: {Name:dependencies Description:Pull requests that update a dependency file Color:0366d6} not changed on exercism/configlet
label: {Name:hacktoberfest-accepted Description: Color:ffffff} not changed on exercism/configlet
label: {Name:x:status/claimed Description:Someone is working on this issue Color:4231af} not changed on exercism/configlet
label: {Name:x:type/ci Description:Work on Continuous Integration (e.g. GitHub Actions workflows) Color:3c2d9f} not changed on exercism/configlet
label: {Name:kind: bug Description:User-facing incorrect behavior Color:e31a1c} not changed on exercism/configlet
label: {Name:x:type/coding Description:Work on code that will run in production Color:3c2d9f} not changed on exercism/configlet
label: {Name:x:type/content Description:Work on content (e.g. exercises, concepts) Color:3c2d9f} not changed on exercism/configlet
label: {Name:x:type/docker Description:Work on Dockerfiles Color:3c2d9f} not changed on exercism/configlet
label: {Name:x:type/docs Description:Work on Documentation Color:3c2d9f} not changed on exercism/configlet
label: {Name:kind: ci Description: Color:ffff99} not changed on exercism/configlet
label: {Name:kind: design Description:Discussing overall direction Color:6a3d9a} not changed on exercism/configlet
label: {Name:kind: docs Description:Changes to documentation Color:cab2d6} not changed on exercism/configlet
label: {Name:kind: feature Description:User-facing enhancement Color:ff7f00} not changed on exercism/configlet
label: {Name:kind: refactor Description:Change to production code that does not fix a bug or add a feature Color:b2df8a} not changed on exercism/configlet
label: {Name:kind: tests Description:Adding or refactoring tests Color:33a02c} not changed on exercism/configlet
label: {Name:priority: high Description:More important Color:fb9a99} not changed on exercism/configlet
label: {Name:status: duplicate Description:This is tracked elsewhere Color:cfd3d7} not changed on exercism/configlet
label: {Name:status: invalid Description:Something that isn't a problem, or isn't due to configlet Color:eeeeee} not changed on exercism/configlet
```

**Comment by ee7** [comment]
Weirdly, I couldn't delete the branch for this PR through the web UI on this page or on https://github.com/exercism/configlet/branches. Even after doing a hard refresh.

But deleting it from the command line worked.

Seems like a GitHub bug.

Note that this says both "there's an open PR" and "merged":

delete-branch

**Pull request merged**
