### PR TITLE
release: 4.0.0-beta.6

### PR DESCRIPTION
**Pull request by ee7**
Let's create a release, mainly for `configlet completion`, https://github.com/exercism/configlet/commit/1ab75f2ba85a84a4c8fdda913186ee93f2cc065e and https://github.com/exercism/configlet/commit/d5f5485f8ced4b69459dcfbbbd0f34a76a0fefda.

The full list of commits that are at least slightly user-facing:

- d5f5485f sync: allow passing both `-uy` and `--tests include|exclude` ([#674](https://github-redirect.dependabot.com/exercism/configlet/pull/674))
- 1ab75f2b generate: allow a concept slug to contain digits ([#664](https://github-redirect.dependabot.com/exercism/configlet/pull/664))
- f4561b01 github(workflows), nimble: bump Nim from 1.6.6 to 1.6.8 ([#666](https://github-redirect.dependabot.com/exercism/configlet/pull/666))
- 5f912658 completions(bash, fish): add zsh completion for -s/--shell ([#659](https://github-redirect.dependabot.com/exercism/configlet/pull/659))
- 88046f46 github(workflows): bump macOS from 11 to 12 ([#597](https://github-redirect.dependabot.com/exercism/configlet/pull/597))
- 6b6a780e github(workflows): bump Ubuntu from 20.04 to 22.04 ([#590](https://github-redirect.dependabot.com/exercism/configlet/pull/590))
- 121b40e4 completions(fish): remove invalid file completions ([#656](https://github-redirect.dependabot.com/exercism/configlet/pull/656))
- e4c86435 completion: add zsh ([#653](https://github-redirect.dependabot.com/exercism/configlet/pull/653))
- 1d689ed4 cli, completion: compress some `const` strings ([#652](https://github-redirect.dependabot.com/exercism/configlet/pull/652))
- 4447bd29 completions: support `completion` subcommand ([#649](https://github-redirect.dependabot.com/exercism/configlet/pull/649))
- 77f7fbf4 completions: make `uuid -n` expect an argument ([#643](https://github-redirect.dependabot.com/exercism/configlet/pull/643))
- d10dcd6d completion: add `configlet completion` subcommand ([#631](https://github-redirect.dependabot.com/exercism/configlet/pull/631))
- 5d98c516 cli: add missing dot in help message ([#644](https://github-redirect.dependabot.com/exercism/configlet/pull/644))
- 690e9e2e completions: add completions for bash and fish ([#629](https://github-redirect.dependabot.com/exercism/configlet/pull/629))

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ee7** [comment]
@ErikSchierboom Do you think we should do anything more before we merge this?

I think we can merge before finishing #647. Then `configlet completion` will be available, but `fetch-configlet` won't tell the user about it yet. I think we can handle updating all the `fetch-configlet` scripts separately, and that doesn't need to block the release. And changing the `fetch-configlet` script in this repo doesn't immediately change the script in every track repo - we need to mass PR.

But maybe we should wait until, say, we update the docs in `exercism/docs`? And this repo? 

The best thing might be for configlet to have per-command help (tracked in #103), and then `configlet completion --help` could print instructions on installing completions. But that isn't going to happen in the immediate future.

**Review by ErikSchierboom — COMMENTED** [review]
> But maybe we should wait until, say, we update the docs in exercism/docs? And this repo?

I think that would probably be wise.

**Comment by ee7** [comment]
Erik agreed last week that we should release.

We should improve the instructions for using `configlet completion`, but it shouldn't block this release.

As usual, I've checked the change that the release produces to the output of `configlet lint` and `configlet sync -o` on every track. No diff, as expected.

Merging soon. Double-checking the release on my fork.

**Comment by ee7** [comment]
Released: https://github.com/exercism/configlet/releases/tag/4.0.0-beta.6

**Pull request merged**
