### PR TITLE
sync: remove `--check` and add `--update`

### PR DESCRIPTION
**Pull request by ee7**
First step towards https://github.com/exercism/configlet/issues/298

---

To-do:
- [x] Amend this part of the README:

> It will then prompt the user to choose whether to include or exclude missing tests, and update the `tests.toml` files accordingly. If you only want a quick check, you can use the `--check` option.

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ee7** [comment]
@ErikSchierboom With https://github.com/exercism/configlet/pull/356/commits/86aa7afc1919c0cf543b2fc1d5685f71e513b136 I've updated the README to remove the mention of `--check`, and explain a bit more.

Any suggested changes?

**Review by ErikSchierboom — APPROVED** [review]
I like it!

**Comment by ee7** [comment]
I changed my mind - I'll make a separate PR for the "explain a bit more" part. I remembered something else I wanted to add too.

I'll merge this PR soon.

**Comment by ErikSchierboom** [comment]
Okay!

**Pull request merged**
