### PR TITLE
.github, cli, completion: cross-compile arm64 Windows asset

### LINKED ISSUE #764: aarch64 build target for release
Hey @ee7 and @ErikSchierboom,

I switched platforms from ubuntu to macOS for my daily driver and noticed that configlet can't be fetched using the included repo script any more.  Reading the documentation, I didn't see any method described to build it from source myself as a very poor `nim` user.

Could you advise?

Thanks

### PR DESCRIPTION
**Pull request by ee7**
Continue the [recent `zig cc` work][1], such that the next configlet release will have two new release assets:

```text
configlet_4.0.0-beta.14_windows_arm64.zip
configlet_4.0.0-beta.14_windows_arm64.zip.minisig
```

where the archive contains the executable:

```console
$ file ./configlet.exe
./configlet: PE32+ executable (console) Aarch64, for MS Windows, 6 sections
```

The `aarch64-windows-gnu` target [will have Tier 1 Zig support][2].

Refs: #24
Refs: #122
Closes: #764

[1]: https://github.com/exercism/configlet/commit/0e8d6659e43dbf0628abcd5ba477e0a011a7058a
[2]: https://ziglang.org/download/0.11.0/release-notes.html#Support-Table

---

To-do:

- [x] Compress as `.zip`, not `.tar.gz`
- [x] Make it actually output a Windows arm64 executable, not x86_64
- [x] Final nitpicks

### CODE REVIEW

**Comment by ee7** [comment]
The build workflow [ran successfully](https://github.com/exercism/configlet/actions/runs/5890212541/job/15974867578) and created [this release](https://github.com/exercism/configlet/releases/tag/untagged-0c20dfb3f77a52083f6f), which ~has an [arm64 Windows asset](https://github.com/exercism/configlet/releases/download/untagged-0c20dfb3f77a52083f6f/configlet_4.0.0-beta.14+w.3_windows_arm64.tar.gz).~ (Edit: it was actually a x86_64 asset in disguise)

@ErikSchierboom Do you have access to an arm64 Windows machine? If so, could you test the above configlet?

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ee7** [comment]
Hmm, why does `file` say that the new executable is `x86-64`?

I'll see if not stripping makes a difference, but I'd guess that the executable really is x86-64 right now.

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom Do you have access to an arm64 Windows machine? If so, could you test the above configlet?

Unfortunately I don't. Maybe ask on the forum?

**Comment by ee7** [comment]
I don't understand why it seems to be [outputting an x86_64 executable](https://github.com/exercism/configlet/actions/runs/5894684581/job/15988813028#step:5:121):

```console
$ .github/bin/cross-compile
[...]
  Executing D:\a\configlet\configlet\nimdir\bin\nim.exe c --colors:on --noNimblePath \
-d:release --cpu:arm64 --os:windows -d:zig -d:target:aarch64-windows-gnu \
-d:NimblePkgVersion=4.0.0 \
--path:C:\Users\runneradmin\.nimble\pkgs2\parsetoml-0.7.1-586fe63467a674008c4445ed1b8ac882177d7103 \
--path:C:\Users\runneradmin\.nimble\pkgs2\jsony-1.1.5-6aeb83e7481ca8686396a568096054bc668294df \
--path:C:\Users\runneradmin\.nimble\pkgs2\supersnappy-2.1.3-36a05ee6befe3764ed8e2a6fb5d0882c2fd090f8 \
-o:D:\a\configlet\configlet\configlet.exe D:\a\configlet\configlet\src\configlet.nim
Hint: used config file 'D:\a\configlet\configlet\nimdir\config\nim.cfg' [Conf]
Hint: used config file 'D:\a\configlet\configlet\nimdir\config\config.nims' [Conf]
Hint: used config file 'D:\a\configlet\configlet\config.nims' [Conf]
...................................................................................................................................................
D:\a\configlet\configlet\src\patched_stdlib\json.nim(1[23](https://github.com/exercism/configlet/actions/runs/5894684581/job/15988813028#step:5:24)3, 7) Hint: 'typInst' is declared but not used [XDeclaredButNotUsed]
...............................................
D:\a\configlet\configlet\nimdir\lib\posix\posix.nim(1155, 13) Hint: 'sig' is declared but not used [XDeclaredButNotUsed]
CC: ../nimdir/lib/system/exceptions.nim
[...]
CC: configlet.nim
Hint:  [Link]
Hint: mm: refc; threads: on; opt: size; options: -d:release
92399 lines; 54.335s; 167.895MiB peakmem; proj: D:\a\configlet\configlet\src\configlet.nim; out: D:\a\configlet\configlet\configlet.exe [SuccessX]
$ llvm-readobj configlet.exe
File: configlet.exe
Format: COFF-x86-64
Arch: x86_64
AddressSize: 64bit
```

**Comment by ErikSchierboom** [comment]
Could it be a Zig issue? Maybe try compiling a non-Nim Zig application first? Just to confirm that Zig can actually do the cross compiling to Windows Arm 64

**Comment by ee7** [comment]
Yeah, Zig can do that. And it works for me locally:

```console
$ nimble build -d:release -d:zig --cpu:arm64 --os:windows -d:target:aarch64-windows-gnu
$ file ./configlet
./configlet: PE32+ executable (console) Aarch64, for MS Windows, 6 sections
$ llvm-readobj ./configlet
File: ./configlet
Format: COFF-ARM64
Arch: aarch64
AddressSize: 64bit
```

So I suspect that we might fix this problem if we cross compile from x86_64 Linux, rather than x86_64 Windows. But I don't know why.

Anyway, I'll try that now.

**Comment by ee7** [comment]
> So I suspect that we might fix this problem if we cross compile from x86_64 Linux, rather than x86_64 Windows. 

Yeah, [that did it](https://github.com/exercism/configlet/actions/runs/5895191139/job/15990411868#step:5:138):

```
configlet: PE32+ executable (console) Aarch64, for MS Windows
```

**Comment by ErikSchierboom** [comment]
Somewhat odd and unexpected, but 🤷‍♂️

**Pull request merged**
