### PR TITLE
github(workflows), nimble: bump Nim from 1.6.4 to 1.6.6

### PR DESCRIPTION
**Pull request by ee7**
Links:
- https://nim-lang.org/blog/2022/05/05/version-166-released.html
- https://github.com/nim-lang/Nim/compare/v1.6.4...v1.6.6
- https://forum.nim-lang.org/t/9144

There are no changes in `lib/pure/{json,parsejson}.nim` for us to port.

Previous Nim bump: #514 

---

~The first Nim `1.6.6` release candidate was released - see [forum post](https://forum.nim-lang.org/t/9100).~

~CI is expected to fail until `1.6.6` is actually released.~

To-do:
- [x] Before merging this PR, merge https://github.com/exercism/configlet/pull/586

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ee7** [comment]
The plan is to release next week: https://forum.nim-lang.org/t/9100#59572

**Comment by ee7** [comment]
Likely bug in `iffy/install-nim` when the binary is not found. It seems to install 1.4.2, rather than erroring.

```
2022-05-04T12:44:45.7841108Z Install type: binary
2022-05-04T12:44:45.7842818Z        param: 1.6.6
2022-05-04T12:44:45.7843663Z install_binary 1.6.6
2022-05-04T12:44:45.7872755Z Found nightly URL for 1.6.6: https://github.com/nim-lang/nightlies/releases/tag/2020-11-30-version-1-4-3fb5157ab1b666a5a5c34efde0f357a82d433d04
2022-05-04T12:44:45.7874051Z Installing prebuilt binaries from: https://github.com/nim-lang/nightlies/releases/tag/2020-11-30-version-1-4-3fb5157ab1b666a5a5c34efde0f357a82d433d04
2022-05-04T12:44:45.7918638Z Archive pattern: linux_x64.tar.xz
2022-05-04T12:44:45.7919773Z tag=2020-11-30-version-1-4-3fb5157ab1b666a5a5c34efde0f357a82d433d04
2022-05-04T12:44:45.8002828Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2022-05-04T12:44:45.8003564Z                                  Dload  Upload   Total   Spent    Left  Speed
2022-05-04T12:44:45.8004504Z 
2022-05-04T12:44:45.9072074Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2022-05-04T12:44:45.9084846Z 100 17778  100 17778    0     0   162k      0 --:--:-- --:--:-- --:--:--  162k
2022-05-04T12:44:45.9137106Z archive_url=https://github.com/nim-lang/nightlies/releases/download/2020-11-30-version-1-4-3fb5157ab1b666a5a5c34efde0f357a82d433d04/nim-1.4.2-linux_x64.tar.xz
2022-05-04T12:44:45.9138329Z archive name: nim-1.4.2-linux_x64.tar.xz
2022-05-04T12:44:45.9139139Z Creating output dir...
2022-05-04T12:44:45.9152240Z Downloading https://github.com/nim-lang/nightlies/releases/download/2020-11-30-version-1-4-3fb5157ab1b666a5a5c34efde0f357a82d433d04/nim-1.4.2-linux_x64.tar.xz ...
2022-05-04T12:44:45.9227240Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2022-05-04T12:44:45.9228097Z                                  Dload  Upload   Total   Spent    Left  Speed
2022-05-04T12:44:45.9228990Z 
2022-05-04T12:44:46.0179317Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2022-05-04T12:44:46.0180714Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2022-05-04T12:44:46.1745534Z 
2022-05-04T12:44:46.1751659Z 100  9.8M  100  9.8M    0     0  39.1M      0 --:--:-- --:--:-- --:--:-- 39.1M
2022-05-04T12:44:46.1783585Z Extracting nim-1.4.2-linux_x64.tar.xz to /home/runner/work/configlet/configlet/nimdir
2022-05-04T12:44:47.0882166Z Setting up PATH
2022-05-04T12:44:47.1059732Z Directory '/home/runner/work/configlet/configlet/nimdir/bin' has been added to PATH.
2022-05-04T12:44:47.1073199Z Directory '/home/runner/work/configlet/configlet/nimdir/bin' has been added to PATH.
2022-05-04T12:44:47.1074014Z Directory '/home/runner/.nimble/bin' has been added to PATH.
2022-05-04T12:44:47.1247586Z Directory '/home/runner/.nimble/bin' has been added to PATH.
```

**Comment by ee7** [comment]
Released just now:
- https://nim-lang.org/blog/2022/05/05/version-166-released.html
- https://github.com/nim-lang/Nim/compare/v1.6.4...v1.6.6

One downside of the new action is that we now require it to be updated first. I've opened a PR for that: 
[iffy/install-nim#21](https://github-redirect.dependabot.com/iffy/install-nim/pull/21).

**Comment by ErikSchierboom** [comment]
> One downside of the new action is that we now require it to be updated first. I've opened a PR for that:
[iffy/install-nim#21](https://github-redirect.dependabot.com/iffy/install-nim/pull/21).

New releases are not _that_ common, are they? So yes: slightly annoying, but not a big deal I think.

There are merge conflicts BTW.

**Comment by ee7** [comment]
> New releases are not _that_ common, are they? So yes: slightly annoying, but not a big deal I think.

Yeah.

```sh
git tag --list --sort=creatordate --format='%(creatordate:short) | %(refname:short)' | tail -n25
```

| Date       | Tag     |
| ---------- | ------- |
| 2019-09-23 | v1.0.0  |  
| 2019-10-23 | v1.0.2  |  
| 2019-11-27 | v1.0.4  |  
| 2020-01-24 | v1.0.6  |  
| 2020-04-03 | v1.2.0  |  
| 2020-06-17 | v1.2.2  |  
| 2020-06-27 | v1.2.4  |  
| 2020-07-30 | v1.2.6  |  
| 2020-07-30 | v1.0.8  |  
| 2020-10-16 | v1.0.10 |   
| 2020-10-16 | v1.2.8  |  
| 2020-10-16 | v1.4.0  |  
| 2020-12-01 | v1.4.2  |  
| 2021-02-23 | v1.4.4  |  
| 2021-02-23 | v1.2.10 |   
| 2021-04-15 | v1.2.12 |   
| 2021-04-15 | v1.4.6  |  
| 2021-05-25 | v1.4.8  |  
| 2021-10-19 | v1.6.0  |  
| 2021-12-03 | v1.2.14 |   
| 2021-12-16 | v1.2.16 |   
| 2021-12-17 | v1.6.2  |  
| 2022-02-09 | v1.6.4  |  
| 2022-02-09 | v1.2.18 |   
| 2022-05-05 | v1.6.6  |

**Comment by ee7** [comment]
@ErikSchierboom Would you like to run `bin/bump_version.nim` now?

**Comment by ErikSchierboom** [comment]
Done https://github.com/exercism/configlet/pull/587

**Pull request merged**
