### PR TITLE
fix: more occurrences of macos12

### PR DESCRIPTION
**Pull request by vaeng**
Missed to files. Thanks @glennj 

> @vaeng Did you miss one? The merge into main is still using v12: https://github.com/exercism/configlet/actions/runs/10903920485/job/30259101645 image

### CODE REVIEW

**Comment by vaeng** [comment]
Something is up with the nim installation on macOS and something else is happening with the windows tests in the nim scripts oO

**Comment by ErikSchierboom** [comment]
You should just rerun the Windows test. It's flaky

**Comment by vaeng** [comment]
> You should just rerun the Windows test. It's flaky

Thanks, I will remember that. The MacOS tests are still not happy though

**Comment by ee7** [comment]
Thanks, but I think we don't want the changes in this PR. The change from `macos-12` to `macos-14` is a change of architecture from `x86_64` to `arm64`, which means:

- The test workflow fails because Nim doesn't provide prebuilt binaries for arm64 macOS.
- The configlet release process will either fail when producing a x86_64-macOS binary, or produce an arm64 macOS binary that is labelled as x86_64-macOS.

Furthermore, it is likely that commit https://github.com/exercism/configlet/commit/22c4cec3d16d155afef664124003a9026b014264 broke the `build.yml` job, which runs at release time (and not at PR time). Changes to that workflow should be tested before being merged. And if we'll build on arm64-macos, we might as well build natively rather than using the cross-compiling machinery.

I think we should close this in favor of https://github.com/exercism/configlet/pull/879. That is, we should move to the non-deprecated macOS x86_64 runner first.

**Comment by vaeng** [comment]
> Thanks, but I think we don't want the changes in this PR. The change from `macos-12` to `macos-14` is a change of architecture from `x86_64` to `arm64`, which means:
> 
>     * The test workflow fails because Nim doesn't provide prebuilt binaries for arm64 macOS.
> 
>     * The configlet release process will either fail when producing a x86_64-macOS binary, or produce an arm64 macOS binary that is labelled as x86_64-macOS.
> 
> 
> Furthermore, it is likely that commit [22c4cec](https://github.com/exercism/configlet/commit/22c4cec3d16d155afef664124003a9026b014264) broke the `build.yml` job, which runs at release time (and not at PR time). Changes to that workflow should be tested before being merged. And if we'll build on arm64-macos, we might as well build natively rather than using the cross-compiling machinery.
> 
> I think we should close this in favor of #879. That is, we should move to the non-deprecated macOS x86_64 runner first.

I did not consider the architecture change in the different os releases, thank you for that pointer. We should probably roll the changes back first and then move on with your suggestion.

**Comment by glennj** [comment]
My apologies for stepping in without knowing the history and build status of this repo.

**Comment by ErikSchierboom** [comment]
For the reasons mentioned by @ee7, I'm closing this.

I've also created https://github.com/exercism/configlet/pull/899 which fixes the build: https://github.com/exercism/configlet/actions/runs/11812866423

**Pull request closed without merging**
